export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const PUT_ITEM = 'PUT_ITEM';
export const INDIVIDUAL_ITEMS = 'INDIVIDUAL_ITEMS';
 
//AUTH ACTION TYPES
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//PROFILES TYPES
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'GET_PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'GET_CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

//POST TYPES
export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//SHIPMENT ACTIONS
export const GET_SHIPMENTS = 'GET_SHIPMENTS';
export const GET_SHIPMENT = 'GET_SHIPMENT';